spring:
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://194.233.65.230:3306/account
    username: dba
    password: e-Gys2023
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true