spring:
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/accountDB
    username: root
    password: asberiyqtsdf
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true